default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: emareb@2018
  host: localhost

development:
  <<: *default
  database: emareb
  password: rootpath

test:
  <<: *default
  database: emareb
  password: rootpath

production:
  <<: *default
  database: emareb